const data = [
  {
    id: 1,
    title: "title1",
    code: "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
    description: "description(asdasdad)",
    language: "language1",
    name: "name1",
  },
  {
    id: 2,
    title: "title2",
    description: "description(cxzczxcwq)",
    language: "language2",
    name: "name2",
  },
  {
    id: 3,
    title: "title3",
    description: "description(zxxcasdqweqwxxzcassdqww)",
    language: "language3",
    name: "name3",
  },
  {
    id: 4,
    title: "title4",
    description:
      "description(asdxcxzcddddddddddddddddddddddddddddddddddddddddddddddddddddddddddasdaaaaaaaaaaaaaaaaasddddddddddddddddddddddddddddddddddddddddddddddddsq)",
    language: "language4",
    name: "name4",
  },
  {
    id: 5,
    title: "title5",
    description: "description",
    language: "language5",
    name: "name5",
  },
  // {
  //   id: 6,
  //   title: "title3",
  //   description: "description(zxxcasdqweqwxxzcassdqww)",
  //   language: "language3",
  //   name: "name3",
  // },
  // {
  //   id: 7,
  //   title: "title5",
  //   description: "description",
  //   language: "language5",
  //   name: "name5",
  // },
  // {
  //   id: 8,
  //   title: "title6",
  //   description: "description(qqqqqqqqqqqqqqqqqqqqqqqqqqqq)",
  //   language: "language6",
  //   name: "name6",
  // },
  // {
  //   id: 9,
  //   title: "title7",
  //   description: "description",
  //   language: "language7",
  //   name: "name7",
  // },
  // {
  //   id: 10,
  //   title: "title4",
  //   description:
  //     "description(asdxcxzcddddddddddddddddddddddddddddddddddddddddddddddddddddddddddasdaaaaaaaaaaaaaaaaasddddddddddddddddddddddddddddddddddddddddddddddddsq)",
  //   language: "language4",
  //   name: "name4",
  // },
  // {
  //   id: 11,
  //   title: "title5",
  //   description: "description",
  //   language: "language5",
  //   name: "name5",
  // },
  // {
  //   id: 12,
  //   title: "title3",
  //   description: "description(zxxcasdqweqwxxzcassdqww)",
  //   language: "language3",
  //   name: "name3",
  // },
  // {
  //   id: 13,
  //   title: "title5",
  //   description: "description",
  //   language: "language5",
  //   name: "name5",
  // },
  // {
  //   id: 14,
  //   title: "title6",
  //   description: "description(qqqqqqqqqqqqqqqqqqqqqqqqqqqq)",
  //   language: "language6",
  //   name: "name6",
  // },
  // {
  //   id: 15,
  //   title: "title7",
  //   description: "description",
  //   language: "language7",
  //   name: "name7",
  // },
  // {
  //   id: 16,
  //   title: "title7",
  //   description: "description",
  //   language: "language7",
  //   name: "name7",
  // },
  // {
  //   id: 17,
  //   title: "title7",
  //   description: "description",
  //   language: "language7",
  //   name: "name7",
  // },
];

export default data;
